<a href="https://colab.research.google.com/github/simionattovini/fluidmechanicspy/blob/main/P1_3a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Robótica Computacional - P1 - Turma de 3a feira**

In [75]:
# Item a)

import numpy as np

def rot_x(angled: float) -> np.ndarray:
  cs = np.cos(angled*np.pi/180)
  sn = np.sin(angled*np.pi/180)
  return np.asarray([[1, 0, 0], [0, cs, sn], [0, -sn, cs]])

def rot_z(angled: float) -> np.ndarray:
  cs = np.cos(angled*np.pi/180)
  sn = np.sin(angled*np.pi/180)
  return np.asarray([[cs, sn, 0], [-sn, cs, 0], [0, 0, 1]])

def cria_vetor3(v: list[float]) -> np.ndarray:
  if len(v) != 3:
    raise ValueError('A lista deveria possuir apenas 3 posições')
  return np.asarray([v]).T

theta_x1 = 53.13
R_I_A = rot_x(theta_x1)
R_I_A = np.round(R_I_A, decimals=2)

theta_z2 = 90
R_A_B = rot_z(theta_z2)
R_A_B = np.round(R_A_B, decimals=2)

theta_x3 = 36.87
R_B_C = rot_x(theta_x3)
R_B_C = np.round(R_B_C, decimals=2)

R_I_C = R_B_C @ R_A_B @ R_I_A
R_C_I = R_I_C.T

print('\n R_I_C = \n\n', R_I_C, '\n\n')
print('\n R_C_I = \n\n', R_C_I, '\n\n')


 R_I_C = 

 [[ 0.    0.6   0.8 ]
 [-0.8  -0.48  0.36]
 [ 0.6  -0.64  0.48]] 



 R_C_I = 

 [[ 0.   -0.8   0.6 ]
 [ 0.6  -0.48 -0.64]
 [ 0.8   0.36  0.48]] 




In [76]:
# Item b) i.

v_c = cria_vetor3([2, -3, 1])
v_i = R_I_C @ v_c

print(v_i)

[[-1. ]
 [ 0.2]
 [ 3.6]]


In [77]:
# Item b) ii.

v_b = cria_vetor3([4, 3, -1])
v_i = R_I_A.T @ R_A_B.T @ v_b

print(v_i)

[[-3. ]
 [ 3.2]
 [ 2.6]]


In [78]:
# Item b) iii.

v_a = cria_vetor3([2, 0, 1])
v_b = R_A_B @ v_a

print(v_b)

[[ 0.]
 [-2.]
 [ 1.]]


In [79]:
# Item b) iv.

v_a = cria_vetor3([0, 1, 1])
v_c = R_B_C @ R_A_B @ v_a

print(v_c)

[[1. ]
 [0.6]
 [0.8]]


In [80]:
# Item c) i.

def norma(v: np.ndarray) -> float:
  return np.sqrt(np.vdot(v, v))

v_a = cria_vetor3([5, -4, 1])

print('A norma do vetor independe da base na qual ele é representado:\n')
print('||v_a|| = ', norma(v_a))
print('||v_b|| = ', norma(R_A_B @ v_a), '\n')
print('Portanto:', '||v_a|| = ||v_b|| = ', norma(v_a))

A norma do vetor independe da base na qual ele é representado:

||v_a|| =  6.48074069840786
||v_b|| =  6.48074069840786 

Portanto: ||v_a|| = ||v_b|| =  6.48074069840786


In [81]:
# Item c) ii.

w_c = cria_vetor3([2, 3, 1])

print('A norma do vetor independe da base na qual ele é representado:\n')
print('||w_c|| = ', norma(w_c))
print('||w_a|| = ', norma(R_A_B.T @ R_B_C.T @ w_c), '\n')
print('Portanto:', '||w_c|| = ||w_a|| = ', norma(w_c))

A norma do vetor independe da base na qual ele é representado:

||w_c|| =  3.7416573867739413
||w_a|| =  3.7416573867739413 

Portanto: ||w_c|| = ||w_a|| =  3.7416573867739413


In [82]:
# Item c) iii.

def proj(a: np.ndarray, b: np.ndarray) -> np.ndarray:
  # Retorna a projeção de a sobre b
  return (np.vdot(a, b)/np.vdot(b, b))*b

v_a = cria_vetor3([5, -4, 1])
w_c = cria_vetor3([2, 3, 1])

print('O tamanho da projeção de um vetor sobre o outro é igual em qualquer ' +
      'base. Ou seja: \n')

print('||proj(v_a, w_a)|| = ', norma(proj(v_a, R_A_B.T @ R_B_C.T @ w_c)))
print('||proj(v_b, w_b)|| = ', norma(proj(R_A_B @ v_a, R_B_C.T @ w_c)))
print('||proj(v_c, w_c)|| = ', norma(proj(R_B_C @ R_A_B @ v_a, w_c)), '\n')

print('Portanto: \n\n||proj(v_a, w_a)|| = ' +
      '||proj(v_b, w_b)|| = ||proj(v_c, w_c)|| = ',
      norma(proj(R_A_B @ v_a, R_B_C.T @ w_c)))

O tamanho da projeção de um vetor sobre o outro é igual em qualquer base. Ou seja: 

||proj(v_a, w_a)|| =  3.8485618835389115
||proj(v_b, w_b)|| =  3.8485618835389115
||proj(v_c, w_c)|| =  3.848561883538911 

Portanto: 

||proj(v_a, w_a)|| = ||proj(v_b, w_b)|| = ||proj(v_c, w_c)|| =  3.8485618835389115


In [84]:
# Item c) iv.

def ang_vetor(a: np.ndarray, b: np.ndarray) -> float:
  return np.arccos(np.vdot(a, b)/(norma(a)*norma(b)))*180/np.pi

v_a = cria_vetor3([5, -4, 1])
w_c = cria_vetor3([2, 3, 1])


print('O ângulo entre dois vetores é o mesmo em qualquer base: \n')

print('ang_vetor(v_a, w_a) = ', ang_vetor(v_a, R_A_B.T @ R_B_C.T @ w_c), '°')
print('ang_vetor(v_b, w_b) = ', ang_vetor(R_A_B @ v_a, R_B_C.T @ w_c), '°')
print('ang_vetor(v_c, w_c) = ', ang_vetor(R_B_C @ R_A_B @ v_a, w_c), '° \n')

print('Portanto: \n')
print('ang_vetor(v_a, w_a) = ang_vetor(v_b, w_b) = ang_vetor(v_c, w_c) = ',
      ang_vetor(v_a, R_A_B.T @ R_B_C.T @ w_c), '°')


O ângulo entre dois vetores é o mesmo em qualquer base: 

ang_vetor(v_a, w_a) =  126.43040907851538 °
ang_vetor(v_b, w_b) =  126.43040907851538 °
ang_vetor(v_c, w_c) =  126.43040907851538 ° 

Portanto: 

ang_vetor(v_a, w_a) = ang_vetor(v_b, w_b) = ang_vetor(v_c, w_c) =  126.43040907851538 °
